#!/bin/bash
# -------------------------------------------------------------------- #
# Syntax: ./new <pkg-scripts-foo>                                      #
#    Will construct a good "skeleton package" which you can then edit  #
#    to add the scripts you want it to contain and their manpages      #
# -------------------------------------------------------------------- #
set -e

pakname=${1}
reponame=${1##pkg-repo-}
distro=`lsb_release -cs`
dir=${PWD}

mkdir ${pakname}
cd ${pakname}
dh_make -s --native --templates ${dir}/templates -c bsd \
        -p ${pakname}_1.0 --rulesformat dh7
rm -f debian/{*.ex,*.EX,README*,changelog,docs}
sed -i 's,<url://example.com>,http://github.com/pkt/pkt-repo-packages,g' debian/copyright
sed -i '4,8d'                      debian/copyright
sed -i '/^# Please also look/d'    debian/copyright
sed -i '/^# different copyright/d' debian/copyright

dch --create --package ${pakname} --newversion 1.0 --distribution ${distro}
sed -i 's/ (Closes.*$//' debian/changelog

cat > Makefile << EOF
distro=\$(shell lsb_release -cs)

all:

install:
	install -d \$(DESTDIR)/etc/apt/sources.list.d/
	install -d \$(DESTDIR)/etc/apt/preferences.d/
	install -d \$(DESTDIR)/usr/share/${pakname}/
	install -m 644 *.list \$(DESTDIR)/etc/apt/sources.list.d/
	install -m 600 30* \$(DESTDIR)/etc/apt/preferences.d/
	install -m 600 *.gpg \$(DESTDIR)/usr/share/${pakname}/
	install -m 600 *.keys \$(DESTDIR)/usr/share/${pakname}/
	for i in *.list ; do sed -i 's/<release>/\$(distro)/g' \$(DESTDIR)/etc/apt/sources.list.d/\$\$i ; done

EOF
